/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_MemAllocAllocatingOneByteIsSuccess(void);
extern void test_MemAllocAllocatingTooMuchMemoryIsError(void);
extern void test_MemCallocAllocatingOneByteIsSuccess(void);
extern void test_MemCallocAllocatingTooMuchMemoryIsError(void);
extern void test_MemFreeDeallocateAllocatedMemoryIsSuccess(void);
extern void test_MemFreePointerAlreadyDeallocatedIsError(void);
extern void test_MemReallocShouldShrinkMemory(void);
extern void test_MemReallocShouldEnlargeMemory(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "TestMem.c";
  UnityBegin();
  RUN_TEST(test_MemAllocAllocatingOneByteIsSuccess, 17);
  RUN_TEST(test_MemAllocAllocatingTooMuchMemoryIsError, 27);
  RUN_TEST(test_MemCallocAllocatingOneByteIsSuccess, 42);
  RUN_TEST(test_MemCallocAllocatingTooMuchMemoryIsError, 51);
  RUN_TEST(test_MemFreeDeallocateAllocatedMemoryIsSuccess, 66);
  RUN_TEST(test_MemFreePointerAlreadyDeallocatedIsError, 77);
  RUN_TEST(test_MemReallocShouldShrinkMemory, 91);
  RUN_TEST(test_MemReallocShouldEnlargeMemory, 104);

  return (UnityEnd());
}
